# Generated by Django 5.1.6 on 2025-11-16 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversacion',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='leido',
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='usuario1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='usuario2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones2', to=settings.AUTH_USER_MODEL),
        ),
    ]
