# Generated by Django 5.1.6 on 2025-11-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0002_remove_conversacion_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='estado',
            field=models.CharField(default='enviado', max_length=10),
        ),
    ]
