# Generated by Django 5.1.6 on 2025-11-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0003_mensaje_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='estado',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('recibido', 'Recibido'), ('visto', 'Visto')], default='enviado', max_length=10),
        ),
    ]
