# Generated by Django 5.2.8 on 2025-12-03 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0005_remove_mensaje_chat_mensaje_destinatario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='mensajeria.chat'),
            preserve_default=False,
        ),
    ]
