# Generated by Django 5.1.6 on 2025-11-26 07:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0005_grupoconversacion_mensajegrupo_oferta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupoconversacion',
            name='oferta',
        ),
        migrations.RemoveField(
            model_name='conversacion',
            name='usuario1',
        ),
        migrations.RemoveField(
            model_name='conversacion',
            name='usuario2',
        ),
        migrations.AddField(
            model_name='conversacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversacion',
            name='participantes',
            field=models.ManyToManyField(related_name='conversaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grupoconversacion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_empresa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grupoconversacion',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='grupoconversacion',
            name='postulantes',
            field=models.ManyToManyField(related_name='grupos_postulante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='conversacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensajeria.conversacion'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='estado',
            field=models.CharField(default='enviado', max_length=20),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha_envio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Oferta',
        ),
    ]
