# Generated by Django 5.2.8 on 2025-12-03 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0006_mensaje_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='destinatario',
        ),
    ]
