# Generated by Django 5.1.6 on 2025-11-26 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0006_remove_grupoconversacion_oferta_and_more'),
        ('ofertas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoconversacion',
            name='oferta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ofertas.ofertalaboral'),
        ),
        migrations.AlterField(
            model_name='grupoconversacion',
            name='postulantes',
            field=models.ManyToManyField(related_name='grupos_postulantes', to=settings.AUTH_USER_MODEL),
        ),
    ]
