# Generated by Django 5.2.8 on 2025-12-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0007_remove_mensaje_destinatario'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos_chat/'),
        ),
    ]
