# Generated by Django 5.2.8 on 2025-12-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0008_mensaje_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='archivo',
        ),
    ]
