# Generated by Django 5.2.8 on 2025-12-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0009_remove_mensaje_archivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['fecha_envio']},
        ),
        migrations.AddField(
            model_name='mensaje',
            name='es_automatico',
            field=models.BooleanField(default=False),
        ),
    ]
