# Generated by Django 5.2.8 on 2025-12-05 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0005_alter_mensaje_remitente'),
        ('mensajeria', '0011_chatbloqueo'),
    ]

    operations = [
    ]
