# Generated by Django 5.2.8 on 2025-12-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0012_merge_0005_alter_mensaje_remitente_0011_chatbloqueo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={},
        ),
        migrations.AddField(
            model_name='chat',
            name='es_automatico',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ChatBloqueo',
        ),
    ]
