# Generated by Django 5.2.8 on 2025-11-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('tipo_empleo', models.CharField(choices=[('formal', 'Formal'), ('temporal', 'Temporal'), ('freelance', 'Freelance'), ('pasantia', 'Pasantía'), ('primer_empleo', 'Primer Empleo')], max_length=50)),
                ('descripcion', models.TextField()),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ubicacion', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='activa', max_length=20)),
            ],
        ),
    ]
