# Generated by Django 5.2.7 on 2025-11-12 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ofertas', '0001_initial'),
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertalaboral',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfiles.perfilempresa'),
        ),
    ]
