# Generated by Django 5.2.8 on 2025-12-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertalaboral',
            name='fecha_expiracion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
