# Generated by Django 5.2.8 on 2025-12-02 22:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0004_favorito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'oferta')},
        ),
        migrations.RemoveField(
            model_name='favorito',
            name='session_key',
        ),
    ]
