# Generated by Django 5.2.8 on 2025-11-27 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ofertas', '0001_initial'),
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfiles.perfilcandidato')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofertas.ofertalaboral')),
            ],
            options={
                'unique_together': {('candidato', 'oferta')},
            },
        ),
    ]
