# Generated by Django 5.1.6 on 2025-11-22 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_initial'),
        ('postulaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoPostulantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_creados', to=settings.AUTH_USER_MODEL)),
                ('miembros', models.ManyToManyField(blank=True, related_name='grupos_postulantes', to=settings.AUTH_USER_MODEL)),
                ('oferta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_postulantes', to='ofertas.ofertalaboral')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupomensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='postulaciones.grupopostulantes')),
            ],
        ),
    ]
