# Generated by Django 5.1.6 on 2025-11-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulaciones', '0002_grupopostulantes_grupomensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupopostulantes',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='grupopostulantes',
            name='miembros',
        ),
        migrations.RemoveField(
            model_name='grupopostulantes',
            name='oferta',
        ),
        migrations.DeleteModel(
            name='GrupoMensaje',
        ),
        migrations.DeleteModel(
            name='GrupoPostulantes',
        ),
    ]
