# Generated by Django 5.2.7 on 2025-11-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(blank=True, max_length=100)),
                ('habilidades', models.TextField(blank=True)),
                ('experiencia', models.TextField(blank=True)),
                ('departamento', models.CharField(blank=True, max_length=50)),
                ('cv_url', models.TextField(blank=True, null=True)),
                ('disponibilidad', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('rubro', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('sitio_web', models.CharField(blank=True, max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('verificada', models.BooleanField(default=False)),
            ],
        ),
    ]
