# Generated by Django 5.2.8 on 2025-11-28 17:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilcandidato',
            options={'ordering': ['-fecha_actualizacion'], 'verbose_name': 'Perfil de Candidato', 'verbose_name_plural': 'Perfiles de Candidatos'},
        ),
        migrations.AlterModelOptions(
            name='perfilempresa',
            options={'ordering': ['-fecha_actualizacion'], 'verbose_name': 'Perfil de Empresa', 'verbose_name_plural': 'Perfiles de Empresas'},
        ),
        migrations.RenameField(
            model_name='perfilempresa',
            old_name='verificada',
            new_name='perfil_completo',
        ),
        migrations.RemoveField(
            model_name='perfilcandidato',
            name='cv_url',
        ),
        migrations.RemoveField(
            model_name='perfilcandidato',
            name='experiencia',
        ),
        migrations.RemoveField(
            model_name='perfilempresa',
            name='contacto',
        ),
        migrations.AddField(
            model_name='perfilcandidato',
            name='biografia',
            field=models.TextField(blank=True, verbose_name='Sobre mí'),
        ),
        migrations.AddField(
            model_name='perfilcandidato',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='CV (PDF)'),
        ),
        migrations.AddField(
            model_name='perfilcandidato',
            name='direccion',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='perfilcandidato',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perfilcandidato',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilcandidato',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='perfilcandidato',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/candidatos/', verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='perfilcandidato',
            name='institucion_educativa',
            field=models.CharField(blank=True, max_length=200, verbose_name='Institución Educativa'),
        ),
        migrations.AddField(
            model_name='perfilcandidato',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='perfilcandidato',
            name='nivel_educacion',
            field=models.CharField(blank=True, choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria/Bachillerato'), ('tecnico', 'Técnico'), ('universitario', 'Universitario'), ('postgrado', 'Postgrado')], max_length=50, verbose_name='Nivel de Educación'),
        ),
        migrations.AddField(
            model_name='perfilcandidato',
            name='perfil_completo',
            field=models.BooleanField(default=False, verbose_name='Perfil Completo'),
        ),
        migrations.AddField(
            model_name='perfilcandidato',
            name='salario_esperado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario Esperado (USD)'),
        ),
        migrations.AddField(
            model_name='perfilcandidato',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Empresa Activa'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='año_fundacion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año de Fundación'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='cantidad_empleados',
            field=models.CharField(blank=True, choices=[('1-5', '1-5 empleados'), ('6-10', '6-10 empleados'), ('11-25', '11-25 empleados'), ('26-50', '26-50 empleados'), ('51-100', '51-100 empleados'), ('100+', 'Más de 100 empleados')], max_length=50, verbose_name='Cantidad de Empleados'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='correo_contacto',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo de Contacto'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='departamento',
            field=models.CharField(blank=True, choices=[('ahuachapan', 'Ahuachapán'), ('cabanas', 'Cabañas'), ('chalatenango', 'Chalatenango'), ('cuscatlan', 'Cuscatlán'), ('la_libertad', 'La Libertad'), ('la_paz', 'La Paz'), ('la_union', 'La Unión'), ('morazan', 'Morazán'), ('san_miguel', 'San Miguel'), ('san_salvador', 'San Salvador'), ('san_vicente', 'San Vicente'), ('santa_ana', 'Santa Ana'), ('sonsonate', 'Sonsonate'), ('usulutan', 'Usulután')], max_length=50, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='direccion',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='documento_verificacion',
            field=models.FileField(blank=True, null=True, upload_to='documentos_empresas/', verbose_name='Documento de Verificación'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='es_verificada',
            field=models.BooleanField(default=False, verbose_name='Empresa Verificada ✓'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='facebook',
            field=models.URLField(blank=True, help_text='URL completa de Facebook', verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='fecha_verificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='instagram',
            field=models.URLField(blank=True, help_text='URL completa de Instagram', verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='linkedin',
            field=models.URLField(blank=True, help_text='URL completa de LinkedIn', verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_empresas/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='mision',
            field=models.TextField(blank=True, help_text='¿Cuál es el propósito de tu empresa?', verbose_name='Misión'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='numero_registro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de Registro/NIT'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='tipo_empresa',
            field=models.CharField(choices=[('formal', 'Empresa Formal Registrada'), ('mype', 'Microempresa o Pequeña Empresa (MYPE)'), ('mype_informal', 'MYPE Informal (En proceso de formalización)')], default='mype', max_length=50, verbose_name='Tipo de Empresa'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='twitter',
            field=models.URLField(blank=True, help_text='URL completa de Twitter', verbose_name='Twitter/X'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='vision',
            field=models.TextField(blank=True, help_text='¿Hacia dónde se dirige tu empresa?', verbose_name='Visión'),
        ),
        migrations.AlterField(
            model_name='perfilcandidato',
            name='departamento',
            field=models.CharField(blank=True, choices=[('ahuachapan', 'Ahuachapán'), ('cabanas', 'Cabañas'), ('chalatenango', 'Chalatenango'), ('cuscatlan', 'Cuscatlán'), ('la_libertad', 'La Libertad'), ('la_paz', 'La Paz'), ('la_union', 'La Unión'), ('morazan', 'Morazán'), ('san_miguel', 'San Miguel'), ('san_salvador', 'San Salvador'), ('san_vicente', 'San Vicente'), ('santa_ana', 'Santa Ana'), ('sonsonate', 'Sonsonate'), ('usulutan', 'Usulután')], max_length=50, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='perfilcandidato',
            name='disponibilidad',
            field=models.CharField(choices=[('inmediata', 'Disponibilidad Inmediata'), ('dos_semanas', 'En 2 semanas'), ('un_mes', 'En 1 mes'), ('buscando', 'Solo explorando opciones')], default='inmediata', max_length=50, verbose_name='Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='perfilcandidato',
            name='habilidades',
            field=models.TextField(blank=True, help_text='Separa tus habilidades con comas. Ej: Python, Django, SQL', verbose_name='Habilidades'),
        ),
        migrations.AlterField(
            model_name='perfilcandidato',
            name='profesion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Profesión u Oficio'),
        ),
        migrations.AlterField(
            model_name='perfilcandidato',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_candidato', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción de la Empresa'),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='nombre_empresa',
            field=models.CharField(max_length=200, verbose_name='Nombre de la Empresa'),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='rubro',
            field=models.CharField(blank=True, choices=[('tecnologia', 'Tecnología e Informática'), ('construccion', 'Construcción'), ('comercio', 'Comercio y Ventas'), ('restaurante', 'Restaurantes y Alimentos'), ('servicios', 'Servicios Profesionales'), ('manufactura', 'Manufactura'), ('agricultura', 'Agricultura'), ('educacion', 'Educación'), ('salud', 'Salud'), ('transporte', 'Transporte y Logística'), ('turismo', 'Turismo y Hotelería'), ('otro', 'Otro')], max_length=50, verbose_name='Rubro'),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='sitio_web',
            field=models.URLField(blank=True, verbose_name='Sitio Web'),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empresa', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_cargo', models.CharField(help_text='Ej: Desarrollador Full Stack, Gerente de Ventas', max_length=200, verbose_name='Título del Cargo')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa/Compañía')),
                ('tipo_empleo', models.CharField(choices=[('tiempo_completo', 'Tiempo Completo'), ('medio_tiempo', 'Medio Tiempo'), ('freelance', 'Freelance/Independiente'), ('practicas', 'Prácticas/Pasantías'), ('temporal', 'Temporal/Por Proyecto')], default='tiempo_completo', max_length=50, verbose_name='Tipo de Empleo')),
                ('sector_industria', models.CharField(blank=True, choices=[('tecnologia', 'Tecnología e Informática'), ('construccion', 'Construcción e Ingeniería'), ('comercio', 'Comercio y Ventas'), ('restaurante', 'Restaurantes y Alimentos'), ('servicios', 'Servicios Profesionales'), ('manufactura', 'Manufactura e Industria'), ('agricultura', 'Agricultura y Ganadería'), ('educacion', 'Educación y Capacitación'), ('salud', 'Salud y Medicina'), ('transporte', 'Transporte y Logística'), ('turismo', 'Turismo y Hotelería'), ('finanzas', 'Finanzas y Banca'), ('marketing', 'Marketing y Publicidad'), ('recursos_humanos', 'Recursos Humanos'), ('legal', 'Legal y Jurídico'), ('arte', 'Arte y Diseño'), ('otro', 'Otro')], max_length=50, verbose_name='Sector/Industria')),
                ('ubicacion', models.CharField(blank=True, help_text='Ciudad, País. Ej: San Salvador, El Salvador', max_length=200, verbose_name='Ubicación')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('trabajo_actual', models.BooleanField(default=False, help_text='Marca si actualmente trabajas aquí', verbose_name='Trabajo Actual')),
                ('descripcion', models.TextField(help_text='Describe tus responsabilidades, logros y actividades principales', verbose_name='Descripción del Puesto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('perfil_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='perfiles.perfilcandidato', verbose_name='Perfil del Candidato')),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Experiencias Laborales',
                'ordering': ['-trabajo_actual', '-fecha_inicio'],
            },
        ),
    ]
