# Generated by Django 5.1.6 on 2025-11-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcandidato',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
