# Generated by Django 5.2.8 on 2025-11-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_perfilcandidato_completado_perfilempresa_completado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilempresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_empresas/'),
        ),
    ]
