# Generated by Django 5.2.8 on 2025-11-28 05:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('empresa', 'Empresa'), ('candidato', 'Candidato')], max_length=20)),
                ('verificado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('codigo_verificacion', models.CharField(blank=True, max_length=6, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('departamento', models.CharField(blank=True, choices=[('ahuachapan', 'Ahuachapán'), ('cabanas', 'Cabañas'), ('chalatenango', 'Chalatenango'), ('cuscatlan', 'Cuscatlán'), ('la_libertad', 'La Libertad'), ('la_paz', 'La Paz'), ('la_union', 'La Unión'), ('morazan', 'Morazán'), ('san_miguel', 'San Miguel'), ('san_salvador', 'San Salvador'), ('san_vicente', 'San Vicente'), ('santa_ana', 'Santa Ana'), ('sonsonate', 'Sonsonate'), ('usulutan', 'Usulután')], max_length=50, verbose_name='Departamento')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='Municipio')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('profesion', models.CharField(blank=True, max_length=200, verbose_name='Profesión u Oficio')),
                ('biografia', models.TextField(blank=True, verbose_name='Sobre mí')),
                ('habilidades', models.TextField(blank=True, help_text='Separa tus habilidades con comas. Ej: Python, Django, SQL', verbose_name='Habilidades')),
                ('nivel_educacion', models.CharField(blank=True, choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria/Bachillerato'), ('tecnico', 'Técnico'), ('universitario', 'Universitario'), ('postgrado', 'Postgrado')], max_length=50, verbose_name='Nivel de Educación')),
                ('institucion_educativa', models.CharField(blank=True, max_length=200, verbose_name='Institución Educativa')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='CV (PDF)')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/candidatos/', verbose_name='Foto de Perfil')),
                ('disponibilidad', models.CharField(choices=[('inmediata', 'Disponibilidad Inmediata'), ('dos_semanas', 'En 2 semanas'), ('un_mes', 'En 1 mes'), ('buscando', 'Solo explorando opciones')], default='inmediata', max_length=50, verbose_name='Disponibilidad')),
                ('salario_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario Esperado (USD)')),
                ('perfil_completo', models.BooleanField(default=False, verbose_name='Perfil Completo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_candidato', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Candidato',
                'verbose_name_plural': 'Perfiles de Candidatos',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_cargo', models.CharField(help_text='Ej: Desarrollador Full Stack, Gerente de Ventas', max_length=200, verbose_name='Título del Cargo')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa/Compañía')),
                ('tipo_empleo', models.CharField(choices=[('tiempo_completo', 'Tiempo Completo'), ('medio_tiempo', 'Medio Tiempo'), ('freelance', 'Freelance/Independiente'), ('practicas', 'Prácticas/Pasantías'), ('temporal', 'Temporal/Por Proyecto')], default='tiempo_completo', max_length=50, verbose_name='Tipo de Empleo')),
                ('sector_industria', models.CharField(blank=True, choices=[('tecnologia', 'Tecnología e Informática'), ('construccion', 'Construcción e Ingeniería'), ('comercio', 'Comercio y Ventas'), ('restaurante', 'Restaurantes y Alimentos'), ('servicios', 'Servicios Profesionales'), ('manufactura', 'Manufactura e Industria'), ('agricultura', 'Agricultura y Ganadería'), ('educacion', 'Educación y Capacitación'), ('salud', 'Salud y Medicina'), ('transporte', 'Transporte y Logística'), ('turismo', 'Turismo y Hotelería'), ('finanzas', 'Finanzas y Banca'), ('marketing', 'Marketing y Publicidad'), ('recursos_humanos', 'Recursos Humanos'), ('legal', 'Legal y Jurídico'), ('arte', 'Arte y Diseño'), ('otro', 'Otro')], max_length=50, verbose_name='Sector/Industria')),
                ('ubicacion', models.CharField(blank=True, help_text='Ciudad, País. Ej: San Salvador, El Salvador', max_length=200, verbose_name='Ubicación')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('trabajo_actual', models.BooleanField(default=False, help_text='Marca si actualmente trabajas aquí', verbose_name='Trabajo Actual')),
                ('descripcion', models.TextField(help_text='Describe tus responsabilidades, logros y actividades principales', verbose_name='Descripción del Puesto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('perfil_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='usuarios.perfilcandidato', verbose_name='Perfil del Candidato')),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Experiencias Laborales',
                'ordering': ['-trabajo_actual', '-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PerfilEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('tipo_empresa', models.CharField(choices=[('formal', 'Empresa Formal Registrada'), ('mype', 'Microempresa o Pequeña Empresa (MYPE)'), ('mype_informal', 'MYPE Informal (En proceso de formalización)')], default='mype', max_length=50, verbose_name='Tipo de Empresa')),
                ('rubro', models.CharField(blank=True, choices=[('tecnologia', 'Tecnología e Informática'), ('construccion', 'Construcción'), ('comercio', 'Comercio y Ventas'), ('restaurante', 'Restaurantes y Alimentos'), ('servicios', 'Servicios Profesionales'), ('manufactura', 'Manufactura'), ('agricultura', 'Agricultura'), ('educacion', 'Educación'), ('salud', 'Salud'), ('transporte', 'Transporte y Logística'), ('turismo', 'Turismo y Hotelería'), ('otro', 'Otro')], max_length=50, verbose_name='Rubro')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción de la Empresa')),
                ('mision', models.TextField(blank=True, help_text='¿Cuál es el propósito de tu empresa?', verbose_name='Misión')),
                ('vision', models.TextField(blank=True, help_text='¿Hacia dónde se dirige tu empresa?', verbose_name='Visión')),
                ('departamento', models.CharField(blank=True, choices=[('ahuachapan', 'Ahuachapán'), ('cabanas', 'Cabañas'), ('chalatenango', 'Chalatenango'), ('cuscatlan', 'Cuscatlán'), ('la_libertad', 'La Libertad'), ('la_paz', 'La Paz'), ('la_union', 'La Unión'), ('morazan', 'Morazán'), ('san_miguel', 'San Miguel'), ('san_salvador', 'San Salvador'), ('san_vicente', 'San Vicente'), ('santa_ana', 'Santa Ana'), ('sonsonate', 'Sonsonate'), ('usulutan', 'Usulután')], max_length=50, verbose_name='Departamento')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='Municipio')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('telefono_contacto', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('correo_contacto', models.EmailField(blank=True, max_length=254, verbose_name='Correo de Contacto')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('facebook', models.URLField(blank=True, help_text='URL completa de Facebook', verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, help_text='URL completa de Instagram', verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, help_text='URL completa de LinkedIn', verbose_name='LinkedIn')),
                ('twitter', models.URLField(blank=True, help_text='URL completa de Twitter', verbose_name='Twitter/X')),
                ('numero_registro', models.CharField(blank=True, max_length=100, verbose_name='Número de Registro/NIT')),
                ('documento_verificacion', models.FileField(blank=True, null=True, upload_to='documentos_empresas/', verbose_name='Documento de Verificación')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_empresas/', verbose_name='Logo')),
                ('es_verificada', models.BooleanField(default=False, verbose_name='Empresa Verificada ✓')),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('cantidad_empleados', models.CharField(blank=True, choices=[('1-5', '1-5 empleados'), ('6-10', '6-10 empleados'), ('11-25', '11-25 empleados'), ('26-50', '26-50 empleados'), ('51-100', '51-100 empleados'), ('100+', 'Más de 100 empleados')], max_length=50, verbose_name='Cantidad de Empleados')),
                ('año_fundacion', models.IntegerField(blank=True, null=True, verbose_name='Año de Fundación')),
                ('perfil_completo', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True, verbose_name='Empresa Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empresa', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Empresa',
                'verbose_name_plural': 'Perfiles de Empresas',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
