# Generated by Django 5.2.8 on 2025-11-28 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilcandidato',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='perfilempresa',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ExperienciaLaboral',
        ),
        migrations.DeleteModel(
            name='PerfilCandidato',
        ),
        migrations.DeleteModel(
            name='PerfilEmpresa',
        ),
    ]
