# Generated by Django 5.1.6 on 2025-11-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('empresa', 'Empresa'), ('candidato', 'Candidato')], default='admin', max_length=20),
        ),
    ]
