# Generated by Django 5.2.7 on 2025-11-24 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='PerfilCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('departamento', models.CharField(blank=True, choices=[('ahuachapan', 'Ahuachapán'), ('cabanas', 'Cabañas'), ('chalatenango', 'Chalatenango'), ('cuscatlan', 'Cuscatlán'), ('la_libertad', 'La Libertad'), ('la_paz', 'La Paz'), ('la_union', 'La Unión'), ('morazan', 'Morazán'), ('san_miguel', 'San Miguel'), ('san_salvador', 'San Salvador'), ('san_vicente', 'San Vicente'), ('santa_ana', 'Santa Ana'), ('sonsonate', 'Sonsonate'), ('usulutan', 'Usulután')], max_length=50, verbose_name='Departamento')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='Municipio')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('profesion', models.CharField(blank=True, max_length=200, verbose_name='Profesión u Oficio')),
                ('biografia', models.TextField(blank=True, verbose_name='Sobre mí')),
                ('habilidades', models.TextField(blank=True, help_text='Separa tus habilidades con comas. Ej: Python, Django, SQL', verbose_name='Habilidades')),
                ('experiencia_laboral', models.TextField(blank=True, verbose_name='Experiencia Laboral')),
                ('nivel_educacion', models.CharField(blank=True, choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria/Bachillerato'), ('tecnico', 'Técnico'), ('universitario', 'Universitario'), ('postgrado', 'Postgrado')], max_length=50, verbose_name='Nivel de Educación')),
                ('institucion_educativa', models.CharField(blank=True, max_length=200, verbose_name='Institución Educativa')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='CV (PDF)')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/candidatos/', verbose_name='Foto de Perfil')),
                ('disponibilidad', models.CharField(choices=[('inmediata', 'Disponibilidad Inmediata'), ('dos_semanas', 'En 2 semanas'), ('un_mes', 'En 1 mes'), ('buscando', 'Solo explorando opciones')], default='inmediata', max_length=50, verbose_name='Disponibilidad')),
                ('salario_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario Esperado (USD)')),
                ('perfil_completo', models.BooleanField(default=False, verbose_name='Perfil Completo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_candidato', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Candidato',
                'verbose_name_plural': 'Perfiles de Candidatos',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='PerfilEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('tipo_empresa', models.CharField(choices=[('formal', 'Empresa Formal Registrada'), ('mype', 'Microempresa o Pequeña Empresa (MYPE)'), ('mype_informal', 'MYPE Informal (En proceso de formalización)')], default='mype', max_length=50, verbose_name='Tipo de Empresa')),
                ('rubro', models.CharField(blank=True, choices=[('tecnologia', 'Tecnología e Informática'), ('construccion', 'Construcción'), ('comercio', 'Comercio y Ventas'), ('restaurante', 'Restaurantes y Alimentos'), ('servicios', 'Servicios Profesionales'), ('manufactura', 'Manufactura'), ('agricultura', 'Agricultura'), ('educacion', 'Educación'), ('salud', 'Salud'), ('transporte', 'Transporte y Logística'), ('turismo', 'Turismo y Hotelería'), ('otro', 'Otro')], max_length=50, verbose_name='Rubro')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción de la Empresa')),
                ('departamento', models.CharField(blank=True, choices=[('ahuachapan', 'Ahuachapán'), ('cabanas', 'Cabañas'), ('chalatenango', 'Chalatenango'), ('cuscatlan', 'Cuscatlán'), ('la_libertad', 'La Libertad'), ('la_paz', 'La Paz'), ('la_union', 'La Unión'), ('morazan', 'Morazán'), ('san_miguel', 'San Miguel'), ('san_salvador', 'San Salvador'), ('san_vicente', 'San Vicente'), ('santa_ana', 'Santa Ana'), ('sonsonate', 'Sonsonate'), ('usulutan', 'Usulután')], max_length=50, verbose_name='Departamento')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='Municipio')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('telefono_contacto', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('correo_contacto', models.EmailField(blank=True, max_length=254, verbose_name='Correo de Contacto')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('numero_registro', models.CharField(blank=True, max_length=100, verbose_name='Número de Registro/NIT')),
                ('documento_verificacion', models.FileField(blank=True, null=True, upload_to='documentos_empresas/', verbose_name='Documento de Verificación')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_empresas/', verbose_name='Logo')),
                ('es_verificada', models.BooleanField(default=False, verbose_name='Empresa Verificada ✓')),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('cantidad_empleados', models.CharField(blank=True, choices=[('1-5', '1-5 empleados'), ('6-10', '6-10 empleados'), ('11-25', '11-25 empleados'), ('26-50', '26-50 empleados'), ('51-100', '51-100 empleados'), ('100+', 'Más de 100 empleados')], max_length=50, verbose_name='Cantidad de Empleados')),
                ('año_fundacion', models.IntegerField(blank=True, null=True, verbose_name='Año de Fundación')),
                ('perfil_completo', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True, verbose_name='Empresa Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empresa', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Empresa',
                'verbose_name_plural': 'Perfiles de Empresas',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
