# Generated by Django 5.2.7 on 2025-11-25 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_codigo_verificacion_perfilcandidato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_cargo', models.CharField(help_text='Ej: Desarrollador Full Stack, Gerente de Ventas', max_length=200, verbose_name='Título del Cargo')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa/Compañía')),
                ('tipo_empleo', models.CharField(choices=[('tiempo_completo', 'Tiempo Completo'), ('medio_tiempo', 'Medio Tiempo'), ('freelance', 'Freelance/Independiente'), ('practicas', 'Prácticas/Pasantías'), ('temporal', 'Temporal/Por Proyecto')], default='tiempo_completo', max_length=50, verbose_name='Tipo de Empleo')),
                ('sector_industria', models.CharField(blank=True, choices=[('tecnologia', 'Tecnología e Informática'), ('construccion', 'Construcción e Ingeniería'), ('comercio', 'Comercio y Ventas'), ('restaurante', 'Restaurantes y Alimentos'), ('servicios', 'Servicios Profesionales'), ('manufactura', 'Manufactura e Industria'), ('agricultura', 'Agricultura y Ganadería'), ('educacion', 'Educación y Capacitación'), ('salud', 'Salud y Medicina'), ('transporte', 'Transporte y Logística'), ('turismo', 'Turismo y Hotelería'), ('finanzas', 'Finanzas y Banca'), ('marketing', 'Marketing y Publicidad'), ('recursos_humanos', 'Recursos Humanos'), ('legal', 'Legal y Jurídico'), ('arte', 'Arte y Diseño'), ('otro', 'Otro')], max_length=50, verbose_name='Sector/Industria')),
                ('ubicacion', models.CharField(blank=True, help_text='Ciudad, País. Ej: San Salvador, El Salvador', max_length=200, verbose_name='Ubicación')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('trabajo_actual', models.BooleanField(default=False, help_text='Marca si actualmente trabajas aquí', verbose_name='Trabajo Actual')),
                ('descripcion', models.TextField(help_text='Describe tus responsabilidades, logros y actividades principales', verbose_name='Descripción del Puesto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('perfil_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='usuarios.perfilcandidato', verbose_name='Perfil del Candidato')),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Experiencias Laborales',
                'ordering': ['-trabajo_actual', '-fecha_inicio'],
            },
        ),
    ]
