# Generated by Django 5.2.8 on 2025-11-28 04:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_solicitudempresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudempresa',
            old_name='correo_corporativo',
            new_name='correo',
        ),
        migrations.AddField(
            model_name='solicitudempresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudempresa',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitudempresa',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudempresa',
            name='nombre_empresa',
            field=models.CharField(max_length=150),
        ),
    ]
