# Generated by Django 5.2.7 on 2025-11-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_experiencialaboral'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcandidato',
            name='es_salvadoreno',
            field=models.BooleanField(default=True, verbose_name='¿Es salvadoreño?'),
        ),
        migrations.AddField(
            model_name='perfilcandidato',
            name='nacionalidad_otra',
            field=models.CharField(blank=True, help_text='Solo si no eres salvadoreño', max_length=100, verbose_name='Otra Nacionalidad'),
        ),
    ]
