# Generated by Django 5.2.7 on 2025-11-26 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfilcandidato_es_salvadoreno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilcandidato',
            name='es_salvadoreno',
        ),
        migrations.RemoveField(
            model_name='perfilcandidato',
            name='nacionalidad_otra',
        ),
    ]
