# Generated by Django 5.2.7 on 2025-11-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_perfilcandidato_es_salvadoreno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilempresa',
            name='facebook',
            field=models.URLField(blank=True, help_text='URL completa de Facebook', verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='instagram',
            field=models.URLField(blank=True, help_text='URL completa de Instagram', verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='linkedin',
            field=models.URLField(blank=True, help_text='URL completa de LinkedIn', verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='mision',
            field=models.TextField(blank=True, help_text='¿Cuál es el propósito de tu empresa?', verbose_name='Misión'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='twitter',
            field=models.URLField(blank=True, help_text='URL completa de Twitter', verbose_name='Twitter/X'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='vision',
            field=models.TextField(blank=True, help_text='¿Hacia dónde se dirige tu empresa?', verbose_name='Visión'),
        ),
    ]
