# Generated by Django 5.1.6 on 2025-11-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_usuario_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
