# Generated by Django 5.2.7 on 2025-11-27 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_perfilempresa_facebook_perfilempresa_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilcandidato',
            name='experiencia_laboral',
        ),
    ]
